services:
  embalagem.api:
    image: embalagem.api
    build:
      context: .
      dockerfile: Embalagem.Api/Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - embalagem-repository-sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=embalagem-repository-sqlserver,1433;Database=Embalagem;User ID=sa;Password=@SuperSecure1;Trusted_Connection=False;TrustServerCertificate=True;
    networks:
      - embalagem-network
    restart: on-failure
  
  
  embalagem-repository-sqlserver:
    image: marvipi/embalagem-repository-sqlserver:dev
    ports:
      - "1433:1433"
    networks:
      - embalagem-network
    volumes:
      - sqlvolume:/var/opt/mssql

networks:
  embalagem-network:

volumes:
  sqlvolume:
