# This is a generated file. Not intended for manual editing.
services:
  embalagem.api:
    build:
      context: "/home/marcus/Dev/l2-embalagem"
      dockerfile: "Embalagem.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "embalagem.api:dev"
    ports:
    - "127.0.0.1:57014:57000"
    - "127.0.0.1:57214:57200"
    - "127.0.0.1:57414:57400"
    volumes:
    - "/home/marcus/Dev/l2-embalagem/Embalagem.Api:/app:rw"
    - "/home/marcus/Dev/l2-embalagem:/src:rw"
    - "/home/marcus/.nuget/packages:/home/app/.nuget/packages"
    - "/home/marcus/.local/share/JetBrains/RiderRemoteDebugger/2024.3.5/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/marcus/.local/share/JetBrains/Toolbox/apps/rider/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/marcus/.cache/JetBrains/Rider2024.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_01_15_09_22:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
